name: Publish to Nuget.org

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish DenDeline.SunMapper to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/SunMapper/SunMapper.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish DenDeline.SunMapper.Common to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/SunMapper.Common/SunMapper.Common.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
